version: '3'

services:
    log-aggregator:
        build:
            context: ./fluentd/
        ports:
            - "42185:42185"
        volumes:
            - ./fluentd.conf:/fluentd/etc/fluent.conf
            - ../log-agg.json:/etc/google/auth/application_default_credentials.json
            - ../log-agg.json:/log-agg.json
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/log-agg.json
            - SETUP_AUTH_FOR_STACKDRIVER=0
        restart: always

    rsyslog-client:
        image: jumanjiman/rsyslog:8.40.0-r3-20190420T1354-git-64eca8b #rsyslog/syslog_appliance_alpine:8.36.0-3.7
        volumes:
            - ./rsyslog_forward.conf:/etc/rsyslog.d/forward.conf
        environment:
            - TZ=UTC
        links:
            - log-aggregator

    read-logs:
        build:
            context: ./readlogs/
        volumes:
            - ../log-agg.json:/etc/google/auth/application_default_credentials.json
            - ../log-agg.json:/log-agg.json
            - ./readlogs/readlogs.py:/readlogs.py
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/log-agg.json
            - LOG_NAME=projects/dhouse-test/logs
